version: '3'

services:
  # frontend:
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: printer_technical_test_frontend
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - ./client/.env
  #   volumes:
  #     - ./client/src:/app/client/src
  #     - ./client/public:/app/client/public
  #   depends_on:
  #     - backend
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    command: dev
    container_name: printer_technical_test_backend
    ports:
      - 3001:3001
    volumes:
      - ./server/src:/app/server/src
    env_file:
      - ./server/.env
  db:
    image: postgres:latest
    container_name: printer_technical_test_db
    env_file:
      - ./server/.env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
    ports:
      - 5432:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    